const message = {
  SOMETHING_WENT_WRONG: 'Something went wrong , server error',
  EMAIL_IS_REGISTERED: 'Email is already registered',
  EMAIL_NOT_REGISTERED: 'Email not registered',
  MOBILE_IS_REGISTERED: 'Mobile number is already registered',
  EMAIL_AND_MOBILE_EXIST: 'Email and mobile number is already taken !',
  NO_USER: 'No admin registered with provided credentials',
  INCORRECT_PASSWORD: 'Incorrect password, please try again !',
  LOGIN_SUCCESS: 'User logged in successfully !',
  ADMIN_FOUND: 'Admin Data found !',
  ADMIN_LIST: 'Admin List !',
  ADMIN_DELETED: 'Admin deleted successfully !',
  INVALID_DATA: 'Invalid request data passed',
  _2FA_CODE_SUCESS: '2FA code sent successfully. !',
  USER_VERIFY_UNSUCESS: 'User not verified. !',
  USER_VERIFY_SUCESS: 'User verified successfully. !',
  USER_OTP_NOT_REMOVED: 'User otp not removed. !',
  ADMIN_REGISTER_SUCCESS: 'Admin created sucessfully',
  ADMIN_UPDATED_SUCCESS: ' Edited Sucessfully',
  TOKEN_NOT_PROVIDED: 'Bearer token not provided',
  TOKEN_UNAUTHORIZED: 'Unauthorized Token',
  UNAUTHORIZED_ROUTE: 'Not elgible for this request',
  ADMIN_ACTIVITY_ADDED: 'Admin Activity added',
  NO_TEMP_PASSWORD_REQUEST: 'No Request for Temporary Password has made !',
  FORGOT_PASSWORD_REQUEST: 'Forgot Password Request sent to Super Admin !',
  USER_ACTIVITY_FETCHED: 'User Activity Fetched Successful',
  USER_ACTIVITY_EMPTY: 'User Activity Is Empty',
}

export default message
